### ISSUE TITLE
Ending text won't display

### ISSUE THREAD

**Issue by Shogun38** [viti95/FastDoom#53]
Hello I'm having an issue with Fast Doom where when I beat an episode in Doom 1 the ending text only displays a single number. Its not locking up or anything it appears to just be an issue with the text. It will display the single number for a bit then move on to the next screen. I've confirmed the doom.wad I use works in vanilla Doom, the ending text will display fine there. Below is a screenshot from the ending screen of episode 2. It did this on the episode 1 ending as well and I'm guessing it will do this for the ending of other episodes. I am playing on AO486 (mister fpga) using Dos 6.22. Below is a screenshot of the issue:

https://i.imgur.com/TpwHDxQ.png

**Comment by viti95** [comment]
Maybe you're missing the INTER folder or one of the text files inside that folder (included in the release). The text of the intermissions are now stored outside the executable, in order to minimize the executable size. If that folder or the text files are missing, the intermission text won't be shown at all.

**Comment by Shogun38** [comment]
Oh how strange everything copied over but that folder. Thanks for that! This wasn't a bug then feel free to close. 

Thanks for making this btw I've really been enjoying playing the DOOM series on the misterfpga with this port.
